spring:
  datasource:
    url: jdbc:mysql://localhost/grupo-1-bdd-oo2-2020?serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

